### ISSUE TITLE
Метод getSumPlayedTime() в классе GameStore не реализован #1

### ISSUE THREAD

**Issue by JulesRu** [JulesRu/QA_team_project#1]
# Описание

Метод getSumPlayedTime() в классе GameStore отсутствует.

# Локация дефекта

https://github.com/JulesRu/QA_team_project/blob/ef8a80e297920afda72c56c7a02bb11a6fa355d7/src/main/java/ru/netology/GameStore.java#L75-L78

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/gamestore/src/main/java/ru/netology/GameStore.java#L75-L78) в IDEA.

*Ожидаемый результат:* метод getSumPlayedTime() суммирует общее количество времени всех игроков, проведённого за играми этого каталога.
*Фактический результат:* метод getSumPlayedTime() полностью отсутствует.

# Скриншот
![ьетод](https://user-images.githubusercontent.com/117368377/220715755-82803ef3-351e-4f83-8950-fc7b3fe5adc5.PNG)

# Окружение

* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by MargaritaRupasova** [comment]
Метод getSumPlayedTime() в классе GameStore реализован
