### ISSUE TITLE
В методе installGame(Game game) в классе Player не реализована возможность возникновения исключительной ситуации, если игра уже была установлена ранее #10

### ISSUE THREAD

**Issue by MargaritaRupasova** [JulesRu/QA_team_project#10]
# Описание
В методе installGame(Game game) в классе Player не реализована возможность возникновения исключительной ситуации, если игра уже была установлена ранее 

# Локализация дефекта
https://github.com/JulesRu/QA_team_project/blob/208197f573608eef9a44ea977252f21aec920215/src/main/java/ru/netology/Player.java#L27-L32

# Шаги воспроизведения
1. Открыть [код программы]( https://github.com/JulesRu/QA_team_project/blob/208197f573608eef9a44ea977252f21aec920215/src/main/java/ru/netology/Player.java) в IDEA.
1. Запустить [тест  shouldNotChangeIfGameAlreadyInstalled()](https://github.com/JulesRu/QA_team_project/blob/208197f573608eef9a44ea977252f21aec920215/src/test/java/ru/netology/PlayerTest.java) в IDEA.
*Ожидаемый результат:* метод installGame(Game game) возвращает RunTimeException при попытке установить игру, если она уже установлена
*Фактический результат:* метод installGame(Game game) устанавливает игру вновь, время игры игрока обнуляется. 

# Скриншот
![image](https://user-images.githubusercontent.com/118010629/223212195-efac4211-4672-420d-bc45-74bafb229e45.png)
![image](https://user-images.githubusercontent.com/118010629/223212347-3e42e725-4b62-4d7a-a86e-678007b5380c.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by JulesRu** [comment]
Метод installGame(Game game) возвращает RunTimeException при попытке установить игру, если она уже установлена.
