### ISSUE TITLE
Метод containsGame в классе GameStore  возвращает значение false для игры, которая является первым объектом в gamestore. #2

### ISSUE THREAD

**Issue by JulesRu** [JulesRu/QA_team_project#2]
# Описание

Метод containsGame не находит объект игры в каталоге GameStore, если игра является первым объектом этого каталога.

# Локация дефекта

https://github.com/JulesRu/QA_team_project/blob/ef8a80e297920afda72c56c7a02bb11a6fa355d7/src/main/java/ru/netology/GameStore.java#L32-L34

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/gamestore/src/main/java/ru/netology/GameStore.java) в IDEA.
2. Открыть также [тест на метод](https://github.com/JulesRu/QA_team_project/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java#L13-L20) в IDEA.
3. Запустить дебаггер теста.
4. Сделать шаг внутрь (Step Into) метода containsGame.

*Ожидаемый результат:* метод containsGame возвращает значение true, подтверждая, что объект игры находится в каталоге.
*Фактический результат:* метод containsGame возвращает значение false, отрицая нахождение игры в каталоге.

# Скриншот
![debug1](https://user-images.githubusercontent.com/117368377/220724102-388b062d-3f41-412b-9606-6688de73be22.PNG)
![debug](https://user-images.githubusercontent.com/117368377/220724167-46930333-7451-401c-9cef-e9e51bd6a9cf.PNG)

# Окружение

* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by MargaritaRupasova** [comment]
Метод containsGame возвращает значение true, подтверждая, что объект игры находится в каталоге.
