### ISSUE TITLE
Метод addPlayTime в классе GameStore при повторном и последующих вызовах не прибавляет часы игры к ранее записанным. #3

### ISSUE THREAD

**Issue by JulesRu** [JulesRu/QA_team_project#3]
# Описание

Метод addPlayTime не суммирует часы игры playedTime: при первом применении метода часы записываются, при повторном вызове метода и попытке добавить ещё часы игры, метод их не сохраняет (записанным playedTime всегда остаются часы, записанные при первичном вызове метода).

# Локация дефекта

https://github.com/JulesRu/QA_team_project/blob/ef8a80e297920afda72c56c7a02bb11a6fa355d7/src/main/java/ru/netology/GameStore.java#L46-L48

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/gamestore/src/main/java/ru/netology/GameStore.java) в IDEA.
2. Открыть также [тест на метод](https://github.com/JulesRu/QA_team_project/blob/ef8a80e297920afda72c56c7a02bb11a6fa355d7/src/test/java/ru/netology/GameStoreTest.java#L78-L89) в IDEA.
3. Запустить дебаггер теста.
4. Сделать шаг внутрь (Step Into) метода addPlayedTime на 84 строке.

*Ожидаемый результат:* метод addPlayedTime прибавляет все повторные записи часов playedTime у каждого игрока, сохраняя сумму всех проигранных игроком часов.

*Фактический результат:* метод addPlayedTime не сохраняет playedTime при повторных вызовах, сохраняются лишь часы playedTime, добавленные при первом вызове метода.

# Скриншот

![debug1](https://user-images.githubusercontent.com/117368377/221186162-94d00583-57a3-4c80-96b2-3f284291aa03.PNG)
![debug2](https://user-images.githubusercontent.com/117368377/221186170-17bb292f-a9ad-404d-aa3c-497e9f2a44f5.PNG)

# Окружение

* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by MargaritaRupasova** [comment]
Метод addPlayedTime прибавляет все повторные записи часов playedTime у каждого игрока, сохраняя сумму всех проигранных игроком часов.
