### ISSUE TITLE
Метод getMostPlayer в классе GameStore не находит bestPlayer, когда наибольшее время игры игрока 1 час #4

### ISSUE THREAD

**Issue by JulesRu** [JulesRu/QA_team_project#4]
# Описание

Метод getMostPlayer не отображает лучшего игрока (игрока, который играл в игры этого каталога больше всего времени), если время игры составляет 1 час.

# Локация дефекта

https://github.com/JulesRu/QA_team_project/blob/b610c45e557d7947a5cd51d9510b2adb6b43dea8/src/main/java/ru/netology/GameStore.java#L58-L60

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA.
2. Открыть также [тест на метод](https://github.com/JulesRu/QA_team_project/blob/ef8a80e297920afda72c56c7a02bb11a6fa355d7/src/test/java/ru/netology/GameStoreTest.java#L56-L63) в IDEA.
3. Запустить дебаггер теста.
4. Сделать шаг внутрь (Step Into) метода store.getMostPlayer на 63 строке.

*Ожидаемый результат:* метод getMostPlayer выдает игрока лучшим, если его время игры - 1 час - является наибольшим среди всех.

*Фактический результат:* метод getMostPlayer не находит лучшего игрока и выдает null, если наибольшее время игрока среди всех - 1 час.

# Скриншот
![debug1](https://user-images.githubusercontent.com/117368377/221192914-bb10e625-4bbc-406e-ac6b-0b8a66c55c88.PNG)
![debug2](https://user-images.githubusercontent.com/117368377/221192919-f9d03697-dd98-47c7-9e0f-1c0a5f32ca3c.PNG)

# Окружение

* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by MargaritaRupasova** [comment]
Метод getMostPlayer выдает игрока лучшим, даже если его время игры - 1 час - является наибольшим среди всех.
