### ISSUE TITLE
Метод mostPlayerByGenre(String genre) в классе Player не реализован #5

### ISSUE THREAD

**Issue by MargaritaRupasova** [JulesRu/QA_team_project#5]
# Описание
Реализация метода mostPlayerByGenre(String genre) в классе Player не соответствует указанному описанию

# Локализация дефекта
https://github.com/JulesRu/QA_team_project/blob/5dfeed26280309ab574ccf8cce7cb8fdb57734ac/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/5dfeed26280309ab574ccf8cce7cb8fdb57734ac/src/main/java/ru/netology/Player.java) в IDEA.

*Ожидаемый результат:* метод mostPlayerByGenre(String genre) принимает жанр и возвращает игру этого жанра, в которую играли больше всего.
*Фактический результат:* метод mostPlayerByGenre(String genre) возвращает null.
 
# Скриншот
![image](https://user-images.githubusercontent.com/118010629/221422777-c6f4abdf-1a53-4e78-817d-3ca249af3671.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by JulesRu** [comment]
Метод mostPlayerByGenre(String genre) в классе Player реализован.
