### ISSUE TITLE
Метод play(Game game, int hours) в классе Player не добавляет время игры, проигранное игроком ранее, #6

### ISSUE THREAD

**Issue by MargaritaRupasova** [JulesRu/QA_team_project#6]
# Описание
Метод play(Game game, int hours) в классе Player не возвращает суммарное количество часов, проигранное игроком в игру 

# Локализация дефекта
https://github.com/JulesRu/QA_team_project/blob/5dfeed26280309ab574ccf8cce7cb8fdb57734ac/src/main/java/ru/netology/Player.java#L33-L34

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/5dfeed26280309ab574ccf8cce7cb8fdb57734ac/src/main/java/ru/netology/Player.java) в IDEA.
1. Запустить [тест  shouldSumPlayTimeIfOneGame()](https://github.com/JulesRu/QA_team_project/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA.

*Ожидаемый результат:* метод play(Game game, int hours) прибавляет время игры, проигранное игроком ранее, и возвращает суммарное количество времени игры данного игрока. 
*Фактический результат:* метод play(Game game, int hours) не прибавляет время игры, проигранное игроком ранее, и возвращает время текущей игры.
 
# Скриншот
![image](https://user-images.githubusercontent.com/118010629/221430643-7e515a4d-4786-4a6e-943e-ac3c42616571.png)
![image](https://user-images.githubusercontent.com/118010629/221430682-c669e4da-dc51-4a88-8122-e01533801feb.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by JulesRu** [comment]
метод play(Game game, int hours) прибавляет время игры, проигранное игроком ранее, и возвращает суммарное количество времени игры данного игрока.
