### ISSUE TITLE
В методе play(Game game, int hours) в классе Player не реализована возможность появления исключительной ситуации, предусмотренной  условием, #7

### ISSUE THREAD

**Issue by MargaritaRupasova** [JulesRu/QA_team_project#7]
# Описание
В методе play(Game game, int hours) в классе Player не реализована возможность появления исключительной ситуации, предусмотренной  условием проекта. По умолчанию игра у игрока  установлена. 

# Локализация дефекта
https://github.com/JulesRu/QA_team_project/blob/5dfeed26280309ab574ccf8cce7cb8fdb57734ac/src/main/java/ru/netology/Player.java#L28-L41

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/5dfeed26280309ab574ccf8cce7cb8fdb57734ac/src/main/java/ru/netology/Player.java) в IDEA.

*Ожидаемый результат:* в случае, если игра не установлена у игрока, метод play(Game game, int hours) должен выкидывать RuntimeException 
*Фактический результат:* в методе play(Game game, int hours) отсутствует возможность выкинуть RuntimeException. 

# Скриншот
![image](https://user-images.githubusercontent.com/118010629/221433590-c665bbe9-df13-4d0f-b638-d2205a4396bf.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by JulesRu** [comment]
Метод play(Game game, int hours) выкидывает RuntimeException в случае, если у игрока не установлена игра.
