### ISSUE TITLE
В методe publishGame в классе Gamestore не реализована возможность возникновения исключительной ситуации, если игра уже была создана ранее. # 9

### ISSUE THREAD

**Issue by JulesRu** [JulesRu/QA_team_project#9]
# Описание

В методе publishGame в классе Gamestore не реализована возможность возникновения исключительной ситуации, если игра уже была установлена ранее.

# Локация дефекта

https://github.com/JulesRu/QA_team_project/blob/a27b02db8985d871e1135343cf56876fd4594876/src/main/java/ru/netology/GameStore.java#L22-L25

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/JulesRu/QA_team_project/blob/gamestore/src/main/java/ru/netology/GameStore.java) в IDEA.

*Ожидаемый результат:* метод publishGame возвращает RunTimeException при попытке создать игру, идентичную уже созданной ранее.
*Фактический результат:* метод publishGame создаёт игру , которая совпадает с уже созданной игрой по всем параметрам.

# Скриншот
![publishGame1](https://user-images.githubusercontent.com/117368377/223198441-439da046-de03-458c-a7c0-fc446171dfb4.PNG)
![publishGame2](https://user-images.githubusercontent.com/117368377/223198447-515b6cfe-5cc6-4c80-a7a3-e6f3c37678fc.PNG)

# Окружение

* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** Java JDK 11

**Comment by MargaritaRupasova** [comment]
Метод publishGame возвращает RunTimeException при попытке создать игру, идентичную уже созданной ранее.
